language: ruby
rvm:
  - 2.3
script:
  - bundle exec jekyll build
  # bundle exec htmlproofer ./_site --only-4xx --check-html
  #--check-favicon
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
