#-------------------------------
# General Site Settings
title: Richard Chiriboga
logo: rc-box.svg # You can add own logo.
description: Richard Chiriboga is a Web Project Manager, Wordpress and Front-End Developer based out of New York City.


#-------------------------------
# Author Settings
author:
  name: Richard Chiriboga
  image: richard-chiriboga.jpg
  say-hello: Hello, I'm <strong>Richard Chiriboga</strong>
  bio: Richard Chiriboga is a combination of multi-disciplines – including strategy, project management and web development.


#-------------------------------
# Contact links
twitter: https://twitter.com/iamchiriboga # Add your Twitter handle
#facebook: https://facebook.com/ # Add your Facebook handle
#dribbble: https://dribbble.com/ # Add your Dribbble handle
#instagram: https://instagram.com/ # Add your Instagram handle
#pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier:  # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: iamchiriboga # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: UA-23366208-1 # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e



#-------------------------------
# Project Settings
project:
  name: Projects
  image: richard-chiriboga.jpg
  header: <strong>Projects</strong> I have worked on
  blurb: During the course of my career, I have worked on and continue to work on some great projects. Here are a few of my favs.

#-------------------------------
# art Settings
art:
  name: Art
  image: chiriboga-art.jpg
  header: Family <strong>Artwork</strong>
  blurb: I am blessed to have a family that is talented in so many areas. Art is one of them. Below are some of the newest art pieces for sale.



#-------------------------------
# About Me Settings
aboutme:
  name: About Me
  image: richard-chiriboga.jpg
  header: About <strong>Richard Chiriboga</strong>
  blurb: Richard Chiriboga is a combination of multi-disciplines – including strategy, project management and web development.